### ISSUE TITLE
makeChildArraysObservable = false still results in observable arrays.

### ISSUE THREAD

**Issue by jbadeau** [coderenaissance/knockout.viewmodel#30]
v2.0.2

using:

ko.viewmodel.options.makeChildArraysObservable = false;

or 

ko.viewmodel.fromModel(model, {makeChildArraysObservable.false});

still results in observable arrays.

**Comment by coderenaissance** [comment]
Sorry to delay so long on this... I've been swamped. I'll try to get this by this weekend.

**Comment by jbadeau** [comment]
No problem :)

**Comment by coderenaissance** [comment]
I have a few unit tests that cover this and they seem to be working, but maybe I'm missing something. Can you share code that shows this is happening? (also sorry for taking so long to follow up, got swamped at work and burnt out, but am back now).

**Comment by coderenaissance** [comment]
I will be releasing the next version this weekend. If you can provide me with code that displays this bug I may be able to squeeze in a fix.

**Comment by jbadeau** [comment]
Sorry was really busy wrapping up development. The issue can be replicated by:

Given model:

``` javascript
var model = {
    "type": "folder",
    "name": "root",
    "children": [
        {
            "type": "folder",
            "name": "sub 1"
        },
        {
            "type": "folder",
            "name": "sub 2",
            "children": [
                {
                    "type": "folder",
                    "name": "sub 1"
                },
                {
                    "type": "folder",
                    "name": "sub 2",
                    "children": []
                }
            ]
        }
    ]
};
```

setting:

``` javascript
ko.viewmodel.options.makeChildArraysObservable = false;
```

and creating a view model like:

``` javascript
ko.viewmodel.fromModel(model, {makeChildArraysObservable.false});
```

or like

``` javascript
ko.viewmodel.fromModel(model);
```

results in the all children array being created as observable.

**Comment by coderenaissance** [comment]
Ok will check it out

**Comment by coderenaissance** [comment]
Ok I see the problem. This flag is was intended to handle nested arrays, which is to say arrays directly within other arrays like this [[3,5],[4,2]]. What you have is arrays with objects in them that have arrays that have objects that have arrays. [{children":[{children":[]}]]}]. I suspect what you want to do is something like this:
<code><pre>
var mappingOptions = {
            custom: {
                "{root}.children": function (children) {
                    var x, newArray = [], length = children ? children.length : 0;
                    for (var x = 0; x < length; x++) {
                        newArray[x] = ko.viewmodel.fromModel(children[x], mappingOptions);
                    }
                    return newArray;
                }
            }
        };

viewmodel = ko.viewmodel.fromModel(model, mappingOptions);

</pre></code>
By doing this none of the arrays would be observable but all other properties would be.

**Comment by jbadeau** [comment]
Thanx allot. I like the plugin very much :)
