### ISSUE TITLE
Please rename project

### ISSUE THREAD

**Issue by ClearCloud8** [coderenaissance/knockout.viewmodel#32]
The name "Knockout Viewmodel" plugin is going to be very confusing to people.  The reason is it will be NEARLY IMPOSSIBLE to google search this plugin and not get mixed results that are simply discussing knockout and viewmodels.

Please consider changing the name to something that doesn't conflict with preexisting vernacular in this domain.  How about Knockout Maptastic?  :)

**Comment by coderenaissance** [comment]
I appreciate the feedback but I'm not seeing a problem. 

The following doesn't show alot of results that are plugin related
    https://www.google.com/search?q=knockout+viewmodel

But if those results are a problem you can do this:
    https://www.google.com/search?q=knockout+viewmodel+-"knockout+viewmodel+plugin"

Also this is a plugin for creating viewmodels in knockout... I want it to show up when people query knockout viewmodel.

Thanks.

**Comment by jimallman** [comment]
For what it's worth, I too found it confusing. But hey, it's good stuff!
