### ISSUE TITLE
Plugin doesn't work with KoLite dirtyFlag as shared function

### ISSUE THREAD

**Issue by corey-cole** [coderenaissance/knockout.viewmodel#36]
I'm attempting to convert an existing knockout.mapping setup to knockout.viewmodel.

I have another model that implements dirtyFlag directly on child array members using the "[i]" syntax and that works just fine.  When I try to implement as a shared function, I get an error of "undefined is not a function".

http://jsfiddle.net/LeCodeNinja/nx2yx/4/

As an aside, I have a question about mapping complex models.  If I need to have more control over creation of a child entity (say there were 4 or 5 more fields in crew that had custom Knockout extensions), what is the best way to do that?  Today, with mapping, I'm shoving that off to a dedicated constructor.  Is that best practice for knockout.viewmodel?

**Comment by darkmyst** [comment]
I believe your problem is a capitalization one. I changed ko.dirtyFlag to ko.DirtyFlag and it started working: http://jsfiddle.net/7wsaM/

**Comment by corey-cole** [comment]
Darn.  Don't I feel stupid.  Thanks!
